Repository Foot-Log/footlog-server, pull requests merged in 2024-08, with the labels that each got.

#2 pr, issue template 생성
  .github/ISSUE_TEMPLATE/⚙️-chore-template.md
  .github/ISSUE_TEMPLATE/🔧-fix-template.md
  .github/ISSUE_TEMPLATE/🔨-refactor-template.md
  .github/ISSUE_TEMPLATE/🛠-feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :page_facing_up: docs

#4 JWTProperties, JWTUtil, TokenProvider 생성
  build.gradle
  src/main/java/footlogger/footlog/domain/jwt/JWTProperties.java
  src/main/java/footlogger/footlog/domain/jwt/JWTUtil.java
  src/main/java/footlogger/footlog/domain/jwt/TokenProvider.java
  src/main/resources/application.yml
Labels: 🛠 feature

#5 카카오 로그인 구현
  src/main/java/footlogger/footlog/config/AppConfig.java
  src/main/java/footlogger/footlog/domain/User.java
  src/main/java/footlogger/footlog/domain/jwt/JWTProperties.java
  src/main/java/footlogger/footlog/repository/UserRepository.java
  src/main/java/footlogger/footlog/service/KakaoService.java
  src/main/java/footlogger/footlog/service/UserService.java
  src/main/java/footlogger/footlog/web/controller/UserController.java
  src/main/java/footlogger/footlog/web/dto/response/UserResponseDto.java
  src/main/resources/application.yml
Labels: 🛠 feature

#7 [Feat] 도메인 생성
  src/main/java/footlogger/footlog/domain/Course.java
  src/main/java/footlogger/footlog/domain/Log.java
  src/main/java/footlogger/footlog/domain/SaveCourse.java
  src/main/java/footlogger/footlog/domain/User.java
Labels: 🛠 feature

#12 base url 지정
  src/main/resources/application.yml
Labels: ⚙ chore

#11 카카오맵 완주한 코스 리스트 반환
  src/main/java/footlogger/footlog/converter/LogConverter.java
  src/main/java/footlogger/footlog/service/LogService.java
  src/main/java/footlogger/footlog/web/controller/LogController.java
  src/main/java/footlogger/footlog/web/dto/response/LogResponseDto.java
Labels: 🛠 feature

#14 지역 코드 변환 기능 추가
  .gitignore
  src/main/java/footlogger/footlog/converter/AreaConverter.java
  src/main/java/footlogger/footlog/utils/areaCodeService.java
Labels: 🛠 feature

#15 카카오 인가 코드 처리 및 디비 유저 저장
  build.gradle
  src/main/java/footlogger/footlog/domain/User.java
  src/main/java/footlogger/footlog/service/KakaoService.java
  src/main/java/footlogger/footlog/web/controller/UserController.java
  src/main/java/footlogger/footlog/web/dto/response/KakaoTokenResponseDto.java
  src/main/java/footlogger/footlog/web/dto/response/KakaoUserInfoResponseDto.java
  src/main/resources/application.yml
Labels: 🛠 feature

#18 유저 정보 확인 구현
  src/main/java/footlogger/footlog/repository/UserRepository.java
  src/main/java/footlogger/footlog/service/KakaoService.java
  src/main/java/footlogger/footlog/service/UserService.java
  src/main/java/footlogger/footlog/web/controller/UserController.java
  src/main/java/footlogger/footlog/web/dto/response/KakaoTokenResponseDto.java
  src/main/java/footlogger/footlog/web/dto/response/UserResponseDto.java
Labels: 🛠 feature

#19 헤더 토큰 이용해서 완주한 코스 리스트 반환
  src/main/java/footlogger/footlog/service/LogService.java
  src/main/java/footlogger/footlog/web/controller/LogController.java
  src/main/resources/application.yml
Labels: 🛠 feature
